efs.extra_field.*.*.*.*.*:
  type: config_entity
  label: 'Extra field config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin:
      type: string
      label: 'Plugin'
    weight:
      type: integer
      label: 'Weight'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    context:
      type: string
      label: 'Context'
    mode:
      type: string
      label: 'Mode'
    field_name:
      type: string
      label: 'Field name'
    settings:
      type: map

efs.extra_field.*.*.*.tokenizer_wysiwyg.*:
  type: config_entity
  label: 'Extra field config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
    plugin:
      type: string
      label: 'Plugin'
    weight:
      type: integer
      label: 'Weight'
    entity_type:
      type: string
      label: 'Entity type'
    bundle:
      type: string
      label: 'Bundle'
    context:
      type: string
      label: 'Context'
    mode:
      type: string
      label: 'Mode'
    field_name:
      type: string
      label: 'Field name'
    settings:
      type: map
      mapping:
        content:
          type: text_format
